[tool.black]
line-length = 100

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
include = [
  "**/django_nlf/**",
]
# Regexes for lines to exclude from consideration
exclude_lines = [
  # Have to re-enable the standard pragma
  "pragma: no cover",

  # Don't complain about missing debug-only code:
  "def __repr__",
  "if self\\.debug",

  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",

  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if __name__ == .__main__.:",
]

[tool.pylint.MASTER]
load-plugins = "pylint_django"
django-settings-module = "tests.settings"

[tool.pylint."MESSAGES CONTROL"]
disable = "duplicate-code"
