name: Lint Python

on:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-django pylint-exit
          pip install -r test_requirements.txt
      - name: Running Pylint
        run: |
          pylint django_nlf || pylint-exit --error-fail $?
