name: Pylint

on:
  push:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # should be 3.x when pylint fixes 3.9 support
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint pylint-exit
        pip install -r test_requirements.txt
    - name: Check formatting with Black
      run: |
        black --check django_nlf tests
    - name: Analysing the code with pylint
      run: |
        pylint django_nlf || pylint-exit --error-fail $?
